### ISSUE TITLE
tdesign icons non resizable

### ISSUE THREAD

**Issue by mainginski** [ng-icons/ng-icons#102]
I appreciate the quick insertion of the Tencent icon pack, but there was a small problem with the inserted icons.

**Describe the bug**
tdesign icons are being restricted to 24px.

**To Reproduce**
`<ng-icon name="tdesignLightingCircle" size="50px"></ng-icon>`
![image](https://github.com/ng-icons/ng-icons/assets/12533589/6ac81499-b47b-40a5-bcb6-4218df008b13)

**Expected behavior**
I validated the ng-icons SVG path and the original Tencent repository path. Only the ng-icon one doesn't resize as expected.
![image](https://github.com/ng-icons/ng-icons/assets/12533589/5735088a-4167-4dc4-b571-5e6bc189dd09)
```
// ng-icons
<svg
  xmlns="http://www.w3.org/2000/svg"
  fill="none"
  view-box="0 0 24 24"
  class="t-icon t-icon-lighting-circle"
  style="width: 32px; height: 32px"
>
  <path
    fill="currentColor"
    d="M12 21a9 9 0 100-18 9 9 0 000 18zm11-9a11 11 0 11-22 0 11 11 0 0122 0zm-10.92 7.5H10v-5H6.29l5.63-10H14v5h3.71l-5.63 10zM12 15.57l2.29-4.07H12V8.43L9.71 12.5H12v3.07z"
  ></path>
</svg>

// original
<svg width="32" height="32" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M12 21C16.9706 21 21 16.9706 21 12C21 7.02944 16.9706 3 12 3C7.02944 3 3 7.02944 3 12C3 16.9706 7.02944 21 12 21ZM23 12C23 18.0751 18.0751 23 12 23C5.92487 23 1 18.0751 1 12C0.999999 5.92487 5.92487 1 12 1C18.0751 0.999999 23 5.92487 23 12ZM12.0848 19.5H10V14.5L6.29015 14.5L11.9152 4.5L14 4.5V9.5L17.7098 9.5L12.0848 19.5ZM12 15.5714L14.2902 11.5H12V8.42862L9.70985 12.5H12L12 15.5714Z" fill="black"/>
  </svg>
```

**Packages:**
 - @ng-icons/tdesign-icons
 - Version latest

**Comment by ashley-hunter** [comment]
Thank you for your feedback! This actually looks like a bug in the tdesign-icons-svg package, for some reason their SVG files contain `view-box` when the correct attribute would be `viewBox`. That being said I have added a step to our SVG processing stage to rename the incorrect attribute to the correct name which should resolve the issue. You should find the fix in the latest patch release.

Any issues, let me know! Thanks
