### ISSUE TITLE
Icon request: HugeIcons

### ISSUE THREAD

**Issue by se1ya** [ng-icons/ng-icons#111]
Many thanks for your awesome package. 

I got another icon set I really think it will fit perfect to your package. 

[Hugeicons](https://hugeicons.com/) 3700 free icons.

**Comment by ashley-hunter** [comment]
Hi, thank you! And thanks for the suggestion. Looks like a good iconset, I was wondering are you aware of any resource for downloading the SVG icons? The website looks like I would have to download each of the icons individually? And the only NPM package available is React only?

**Comment by se1ya** [comment]
Hi Ashley,
I created a little program to download the complete free iconSet. Is it fine to attach it here?

**Comment by ashley-hunter** [comment]
Hi, thank you! Sure! Go right ahead, and I'll see if I can integrate it 😊

**Comment by se1ya** [comment]
Here is the free stroke rounded icons set 

[hugeicons-svgs.zip](https://github.com/ng-icons/ng-icons/files/15447127/hugeicons-svgs.zip)

**Comment by ashley-hunter** [comment]
Thanks for the help! The icons should now be available!
