### ISSUE TITLE
Error: export 'firstValueFrom' (imported as 'firstValueFrom') was not found in 'rxjs'

### ISSUE THREAD

**Issue by nikita-fuchs** [ng-icons/ng-icons#120]
**Describe the bug**
Using Angular 16, I cannot build my application utilising ng-icons as ng-icons errors: 

`./node_modules/@ng-icons/core/fesm2022/ng-icons-core.mjs:120:11-25 - Error: export 'firstValueFrom' (imported as 'firstValueFrom') was not found in 'rxjs'`

This is because `firstValueFrom` was introduced in rxjs v7, which the package [correctly requires.](https://github.com/ng-icons/ng-icons/blob/v25.6.1/package.json)

I did not get any errors during the installation of ng-icons though about my project still being on rxjs 6.5.5. I'm not a fully blown NPM pro, but shouldn't the package manager either complain oder bring its own version or something?

**To Reproduce**
1. Have rxjs 6.x.x in your project
2. install ng-icons @ 25
3. Import an icon and try building

**Expected behavior**
Everything should build

**Packages (please complete the following information):**
 - @ng-icons/css.gg
 - ng-icons @ 25
 
**additional info**
Running 

`npm list rxjs` doesnt list ng-icons for some reason:

```
├─┬ @aeternity/aepp-sdk@13.3.2
│ └─┬ @ledgerhq/hw-transport@6.30.6
│   └─┬ @ledgerhq/devices@8.3.0
│     └── rxjs@7.8.1
├─┬ @angular-devkit/build-angular@16.2.6
│ ├─┬ @angular-devkit/architect@0.1602.6
│ │ └── rxjs@7.8.1
│ ├─┬ @angular-devkit/build-webpack@0.1602.6
│ │ └── rxjs@7.8.1
│ ├─┬ @angular-devkit/core@16.2.6
│ │ └── rxjs@7.8.1
│ ├─┬ inquirer@8.2.4
│ │ └── rxjs@7.8.1
│ └── rxjs@7.8.1
├─┬ @angular-devkit/schematics@16.2.6
│ └── rxjs@7.8.1
├─┬ @angular/cdk@15.2.9
│ └── rxjs@6.6.7 deduped
├─┬ @angular/common@16.2.9
│ └── rxjs@6.6.7 deduped
├─┬ @angular/core@16.2.9
│ └── rxjs@6.6.7 deduped
├─┬ @angular/flex-layout@15.0.0-beta.42
│ └── rxjs@6.6.7 deduped
├─┬ @angular/forms@16.2.9
│ └── rxjs@6.6.7 deduped
├─┬ @angular/router@16.2.9
│ └── rxjs@6.6.7 deduped
├─┬ codelyzer@6.0.2
│ ├─┬ @angular/core@9.0.0
│ │ └── rxjs@6.6.7 deduped
│ └── rxjs@6.6.7 deduped
├─┬ ng-circle-progress@1.7.1
│ └── rxjs@6.6.7 deduped
├─┬ ng-inline-svg-2@15.0.1
│ └── rxjs@6.6.7 deduped
├─┬ ng-inline-svg@10.1.0
│ └── rxjs@6.6.7 deduped
├─┬ ngx-ng2-semantic-ui@16.0.1
│ └── rxjs@6.6.7 deduped
└── rxjs@6.6.7
```

**Comment by ashley-hunter** [comment]
Thank you very much for the bug report, you are correct, the peer dependencies section seems to have been accidentally removed in the core library. I'm travelling until early next week, I will resolve this when I return. Thank you!

**Comment by nikita-fuchs** [comment]
Thank you ! What's a bit weird is that I can't seem to edit `./node_modules/@ng-icons/core/fesm2022/ng-icons-core.mjs` for a quick temporary fix, e.g. by making it import rxjs from an alias package instead, or straight copy-pasting `firstValueFrom()` into that module and make the code use that function. It will still throw that error, even though I've changed the code completely. Even changing all `rxjs` imports inside the package doesn't do the trick. I'm not a super pro with NPM thus can't figure out what's the issue here. I'm wondering if I can just add rxjs 7 as a dependency and build the package myself, if just patching things inside the package doesn't work for some reason? Instead of putting it as a peerDependency, as my project most likely would break on moving away from rxjs 6.6 .

**Comment by ashley-hunter** [comment]
Thank you very much for your sponsor; very much appreciated! Glad you found a workaround! When I return I can change this to support rxjs 6 and 7, and can back port it to v25 so you won't need your workaround for long.
