### ISSUE TITLE
`provideNgIconLoader` not working with SSR

### ISSUE THREAD

**Issue by DerHerrGammler** [ng-icons/ng-icons#122]
**Describe the bug**
If you configure the default icon loader function like in the dokumentation the following error comes up:
```shell
ERROR RuntimeError: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.dev/errors/NG0203
```

**To Reproduce**
1. Create a SSR application
2. Add the default `provideNgIconLoader()` from the documentation
3. Start the application

**Expected behavior**
It should at least also try to get the icon in SSR mroe.

**Browser (please complete the following information):**
 - OS: Windows
 - Browser FireFox
 - Version current

**Packages (please complete the following information):**
 - @ng-icons/core
 - Version 29

**Additional context**

**Comment by ashley-hunter** [comment]
Hi! Thank you for the bug report! If you are using AnalogJS this has been known to happen and a solution can be found here:

https://github.com/ng-icons/ng-icons/issues/58#issuecomment-1545599753

I did try to reproduce this in standard Angular SSR project here, but it appears to be be working as expected:

https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-cbf9f2?file=README.md

If you are able to reproduce the issue I'll be happy to investigate! Thanks

**Comment by DerHerrGammler** [comment]
Ah yea I'm using AnalogJS. Thanks for the link to the solution, din't found that myself

**Comment by ashley-hunter** [comment]
No problem! Glad the issue is resolved!
