### ISSUE TITLE
Fuzzy search returns too much noise

### ISSUE THREAD

**Issue by rg-lahcene** [ng-icons/ng-icons#123]
This is not a bug in itself but from a usuability point of view, the fuzzy search returns too much noisy results and make the experience of looking up for icons worse.

using the old approach of substring matching would be great

![image](https://github.com/user-attachments/assets/2576112f-0e05-4b8f-99ab-1bf8af98b458)

**Comment by ashley-hunter** [comment]
Thank you for the suggestion! You are absolutely right, the threshold was set far too high, I have now reduced it which should hopefully yield much better results. If you find this is still not satisfactory let me know and I can take another look.
