### ISSUE TITLE
Angular @Defer not show icons

### ISSUE THREAD

**Issue by enrico-bellanti** [ng-icons/ng-icons#126]
I cannot see icons when use functionality @Defer in Angular.

- wrap component which contains icons with @Defer on viewport
- when show component icon do not apper
- in console i see it tried to get icon with NgIconLoader but it is not a custom icon provided in the asset
- all the icons that i use have been taken from standard package ng-icons/bootstrap-icons
![image](https://github.com/user-attachments/assets/8f5da1ba-8faa-42e8-a37f-0a7e629c9196)

![image](https://github.com/user-attachments/assets/078550e3-750d-4fad-9003-c1dafa0590e8)

**Packages (please complete the following information):**
 - "@ng-icons/core": "^28.1.0",
 - "@angular/common": "^18.0.5",
 - "@ng-icons/bootstrap-icons": "^28.1.0",

All the rest of icons work perfectly and are imported in the same way, i just supposed the problem would be in that point because is the only one of the entire app with @Defer

**Comment by ashley-hunter** [comment]
Closing for now - if the issue persists after the suggested fix above let me know and I will re-open, thanks.
