### ISSUE TITLE
 want to  add one more package of custom library icon

### ISSUE THREAD

**Issue by chits1612** [ng-icons/ng-icons#137]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser (please complete the following information):**

**Packages (please complete the following information):**
 - @ng-icons/material-icons
 - Version [e.g. 13.0.0]

**Additional context**

**Comment by ashley-hunter** [comment]
Hi, I'm not quite sure what the request is here? Would you mind providing some additional information and I'll see if I can accommodate your request. Thanks

**Comment by chits1612** [comment]
there are lots of packages of icons like material-icons,iconsax and many more , just like this if i want to add more one packages then what would be the process

**Comment by ashley-hunter** [comment]
Hey, so I have added a contributing guide to the repo you can find here:
https://github.com/ng-icons/ng-icons/blob/main/CONTRIBUTING.md

Hopefully that helps you, but if you have any specific questions just ask 😊
