### ISSUE TITLE
Wrong name for "lucideChartPie"

### ISSUE THREAD

**Issue by wandri** [ng-icons/ng-icons#148]
**Describe the bug**

**To Reproduce**
1. Go to 'https://ng-icons.github.io/ng-icons/#/browse-icons',
2. Filter by Lucide icons
3. Click on "lucidePieChart"

**Expected behavior**

- "**lucidePieChart**" can be used as import name.

But it doesn't exist. Instead, "**lucideChartPie**" exists. (see https://github.com/search?q=repo%3Ang-icons%2Fng-icons+lucideChartPie&type=code)

**Comment by ashley-hunter** [comment]
Thank you for the report, the documentation site has now been updated to show the correct icons.
