### ISSUE TITLE
colorful crypto icons

### ISSUE THREAD

**Issue by jozefRudy** [ng-icons/ng-icons#151]
i can only get black and white crypto icons.
could we also add colored crypto icons?

**Comment by ashley-hunter** [comment]
Hey! Angular Icons repackages existing iconsets in a compatible way, we don't create the icons. The crypto icons come from this iconset:
http://cryptoicons.co/

Unfortunately they don't offer a colored set. You can simply color the icons yourself using the CSS color property. Alternatively, you could request a colored set on their repository, if they provide one I'll gladly make it available! 

Or if you're aware of a colored iconset that meets your needs let me know and I can add it!

Thanks

**Comment by ashley-hunter** [comment]
Ah cool, thank you, I was not aware of this. I'll look into it, thanks!

**Comment by jozefRudy** [comment]
thank you!

**Comment by ashley-hunter** [comment]
Thanks, these should now be available in the v29.8.0 release
