### ISSUE TITLE
Support Game Icons

### ISSUE THREAD

**Issue by seiyria** [ng-icons/ng-icons#153]
It would be awesome to have support for [game icons](https://game-icons.net/). Is this something possible for this library?

**Comment by seiyria** [comment]
Hey, thanks for adding this. I don't seem to be able to `npm i @ng-icons/game-icons`. Does it take some time to get the package uploaded? Either way, very exciting!

**Comment by ashley-hunter** [comment]
Hey, no problem! Yes, it should just be published there now 😊 if you try installing now it should work. Any issues let me know!
