### ISSUE TITLE
Icon Request: Flag Icons

### ISSUE THREAD

**Issue by robbie-andersen** [ng-icons/ng-icons#155]
Loving the package so far!

Problem: Chromium browsers (Chrome/Edge) do not ship with their own flag icon set - Issue: [https://issues.chromium.org/issues/40766658](https://issues.chromium.org/issues/40766658). Example: 🇦🇺 🏴󠁧󠁢󠁳󠁣󠁴󠁿 🇫🇮 (switch between browsers to see flag icons on Firefox and 2 letter country codes on Chromium)

Proposal: Integrate a flag icon set for localisation styling across browsers. An icon set I suggest is Lipis' Flag Icons library which is open-source and very active - Web: [https://flagicons.lipis.dev/](https://flagicons.lipis.dev/l), Github: [https://github.com/lipis/flag-icons](https://github.com/lipis/flag-icons)

**Comment by ashley-hunter** [comment]
Thank you, good suggestion. I have added this library in 29.10.0, any issues just let me know, thanks!
