### ISSUE TITLE
Please shorten the animation on the website, it is really annoying to wait

### ISSUE THREAD

**Issue by samuelmoser** [ng-icons/ng-icons#156]
I like your library a lot. But the animation on the website is too slow...

**Comment by ashley-hunter** [comment]
Thanks, yes, been meaning to fix this for a while, it wasn't too bad at the start, but as I have added content over time it has become too slow. I have speed it way up - hopefully that is better, if not feel free to let me know.

**Comment by samuelmoser** [comment]
Thanks a lot. It's much better now :-)
