### ISSUE TITLE
size doesnt work in firefox

### ISSUE THREAD

**Issue by henrysachs** [ng-icons/ng-icons#16]
first of all thanks for this great library! I had a pleasure using it.

**Describe the bug**
when using firefox and the size attribute the icons are way to big.

**To Reproduce**
1. Go to https://github.com/henrysachs/tailwindtuts/tree/9714c3a490af4cf2ad5597ad97cb5e0aa1b77352
2. run npm install and npm run start
3. open page with firefox (i used the developer edition) at localhost:4200
4. See error icons are way to big 

**Expected behavior**
the size that was set for the icons is applied

**Screenshots**

![ng-icons-bug](https://user-images.githubusercontent.com/17173951/147573740-a081e9fd-f68e-48f6-83d0-e55283e96fc1.PNG)
![unknown](https://user-images.githubusercontent.com/17173951/147573743-cd0095e9-33cb-4815-98da-0a23b58fba0a.png)

**Browser (please complete the following information):**
 - Windows
 - Firefox in developer or non developer edition see screenshots from 2 systems
 
**Packages (please complete the following information):**
 - @ng-icons/hero-icons
 - tailwindcss

**Additional context**
happy to provide more information if needed
i fixed it by now by setting the text size via css and not via the size property. thats why i linked an explicit commit

**Comment by ashley-hunter** [comment]
Thanks very much for the detailed bug report. I have pushed a fix and released a new update. Hopefully that resolves your issue, if not let me know and I'll reopen the issue.

**Comment by henrysachs** [comment]
will check it out thanks a lot for the fast response!
