### ISSUE TITLE
Solar duotone is not displayed correctly

### ISSUE THREAD

**Issue by anversoft** [ng-icons/ng-icons#162]
Would it be possible to also integrate the Line Duotone from the [solar icon set](https://github.com/480-Design/Solar-Icon-Set/tree/main/icons/SVG/Line%20Duotone)?

Thank you so much for your work on this awesome package!

**Comment by anversoft** [comment]
Okay, Duotone is already the line Duotone, but the Duotone icon set is identical to the Bold Duotone icon set.

![image](https://github.com/user-attachments/assets/58723a52-0140-4f0a-9223-76f8d1d9c4e6) 
![image](https://github.com/user-attachments/assets/17b0c5f4-23a3-4ff4-9fc1-051f9a13d6c1)

Instead of the correct icon
![image](https://github.com/user-attachments/assets/99e50368-628b-43fa-b3a8-0bed6353023f)

Is it also possible to change the opacity parameter of the svg?

**Comment by ashley-hunter** [comment]
Thank you, I'll look into it, the iconsets that were not included were not rendering well at all and had several issues. Looks like I missed that issue with the duotone and duotone bold being the same. I'll see if I can resolve issues.

**Comment by ashley-hunter** [comment]
I have just pushed a release that should hopefully resolve these issues, if I have missed anything just let me know.

**Comment by anversoft** [comment]
> I have just pushed a release that should hopefully resolve these issues, if I have missed anything just let me know.

It works, thank you so much!

**Comment by ashley-hunter** [comment]
Excellent! No problem, thanks for reporting it!
