### ISSUE TITLE
Wrong Material icon names in version 13.2.0

### ISSUE THREAD

**Issue by Trivernis** [ng-icons/ng-icons#18]
**Describe the bug**
The names of all material icons changed the following way:
`MatAddCircle` -> `MatNodeModulesMaterialIconsSvgSvgAddCircle`
`MatDeleteSweep` -> `MatNodeModulesMaterialIconsSvgSvgDeleteSweep`

**To Reproduce**
1. Look at [this file](https://github.com/ng-icons/ng-icons/blob/master/packages/material-icons/src/index.ts)

**Expected behavior**
The names stay the way they were defined before. E.g `MatAddCircle`.

**Packages (please complete the following information):**
 - @ng-icons/material-icons
 - Version 13.2.0

**Comment by ashley-hunter** [comment]
Thanks for the bug report, apologies for the inconvenience, I'll get an update out with a fix within the next few hours.

**Comment by ashley-hunter** [comment]
That should be the issue resolved and a new version released. I have added additional test coverage to prevent such an issue reoccurring. Let me know if you have any further issues, thanks.
