### ISSUE TITLE
Outdated Octicons

### ISSUE THREAD

**Issue by haythem** [ng-icons/ng-icons#23]
**Describe the bug**
The `npm` library for `octicons` is outdated and has been replaced by a new set under `@primer/octicons` npm package.

**Packages**
 - @ng-icons/octicons

**Comment by ashley-hunter** [comment]
Thank you for bringing this to my attention, I will get this updated.

**Comment by ashley-hunter** [comment]
I have just released an updated version of the package that contains the latest version of the octicons icons. Thanks

**Comment by haythem** [comment]
@ashley-hunter, that was fast 👍 😄 

Thank you very much. Keep up the good work.
