### ISSUE TITLE
HeroXSolid / HeroXCircleSolid icons not working when using NgIconsModule.withIcons({})

### ISSUE THREAD

**Issue by hansschollaardt** [ng-icons/ng-icons#30]
**Describe the bug**
When using HeroXSolid / HeroXSolidShield icons, they will not show even though they were added to the `NgIconsModule.withIcons({<icons>});` function. Any other icon will work without issues, even the outline variant: `hero-x` / `HeroX`. 

**To Reproduce**
1. Add an ng-icon using `hero-xsolid` and/or `hero-xsolid-shield` to a page
```
        <ng-icon name="hero-xcircle-solid"></ng-icon>
        <ng-icon name="hero-xsolid"></ng-icon>
```
3. Include the icons in the NgIconsModule.withIcons definition:
```
        NgIconsModule.withIcons({
            HeroXSolid,
            HeroXCircleSolid
        })
```
4. Open the browser console and find the issue as provided under the screenshot section.

Any other (solid) icon will work correctly. I haven't found any others that show this issue but I cannot rule them all out as we use a limited set of hero-icons

**Expected behavior**
The inclusion of the `hero-xcircle-solid` and `hero-xcircle` works without issues. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6661700/177994933-c028baf8-7059-4d7d-9748-cbcd65ec3279.png)
![image](https://user-images.githubusercontent.com/6661700/177993906-ada205b9-9882-4b79-ad6e-47c42e277695.png)

**Browser (please complete the following information):**
 - OS: Windows (not OS related)
 - Browser: chrome, edge, firefox] (not browser related)
 - Version: (Chrome) 103.0.5060.66

**Packages (please complete the following information):**
 - @ng-icons/core v15.1.0
 - @ng-icons/heroicons v15.1.0
 - Version [e.g. 13.0.0]

**Additional context**
Angular v13.3.8

**Comment by ashley-hunter** [comment]
Hi, thank you for the bug report. I think this may be an issue with the documentation. Could you try the following instead with a hyphen after the `x`:

`hero-x-circle-solid`

**Comment by hansschollaardt** [comment]
I did, but it does not work. The icons are exported with a different name: 
![image](https://user-images.githubusercontent.com/6661700/177998893-107bf1e3-0063-439e-b844-49b5103f5e07.png)
![image](https://user-images.githubusercontent.com/6661700/177998994-f99446ba-3205-4a2e-a750-85eaf593cfb9.png)
See `icon-name.ts` definitions

**Comment by ashley-hunter** [comment]
Yes, the names you see there are generated the same way as the names in the docs site, so have the same incorrect naming. We provide those to give extra help in the autocomplete list in your screenshot, but we also allow any string there to allow custom icons to be registered, or icons to be renamed etc..

So while `hero-x-circle-solid` May not appear in that list you can still use it. For example you can see using the corrected names works as expected:

https://stackblitz.com/edit/angular-ivy-fddncm?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html

I will correct this in both the docs and auto completion. I'm currently travelling so it will be a week or two before the next release, but hopefully this workaround will suffice for the time being. Thanks for the feedback!

**Comment by ashley-hunter** [comment]
Thank you 😊
