### ISSUE TITLE
Icon library request: Circum Icons

### ISSUE THREAD

**Issue by Klarr-Agency** [ng-icons/ng-icons#43]
Hi there,
I'm the maintainer of Circum Icons a library of 285 icons. You can see them at [circumicons.com](https://circumicons.com) and you can find our repo [here](https://github.com/Klarr-Agency/Circum-Icons). Our icons are available for React, Vue and Svelte. It would be nice to have an alternative for Angular.

Let me know if I can do something.

Thank you!
![Circum_Free-1](https://user-images.githubusercontent.com/87146097/197282218-382a1949-b601-48e2-aa61-6581b3403a67.jpg)

**Comment by ashley-hunter** [comment]
Thank you for your suggestion! I'm always looking for high quality iconsets to add to the project and I hadn't come across this one before. Looks great, certainly one I will use myself in future!

I have added your iconset which should now be available to view here and the package should be available on NPM:
https://ng-icons.github.io/ng-icons/#/circum-icons

Let me know if you encounter any issues! Thanks!

**Comment by Klarr-Agency** [comment]
Wow that was fast! Thank you for the kind words @ashley-hunter, I'm glad that you like it. Just one thing, I feel bad about asking it, but could you add our website url in your README.md like the others?
![image](https://user-images.githubusercontent.com/87146097/197295129-15f8c116-3b08-4455-ae35-2a1dda998b27.png)

Thank you again and have a nice day!

**Comment by ashley-hunter** [comment]
Apologies, I forgot to do that, will update it now 😊.

**Comment by ashley-hunter** [comment]
Done 😊

**Comment by Klarr-Agency** [comment]
No problem, thank you! 😃
