### ISSUE TITLE
@ng-icons/lucide for Angular 16

### ISSUE THREAD

**Issue by svensken94** [ng-icons/ng-icons#55]
**Describe the bug**
I'm using the **@ng-icons/lucide** icon collection in my Angular 16 project. I assume **@ng-icons/lucide** has not been updated yet for Angular 16. I am getting an error when running the `npm install` command.

**To Reproduce**
1. Create new project with **Angular 16**
2. Run `npm i @ng-icons/core @ng-icons/lucide`
3. See error

**Screenshots**
![eresolve-report](https://user-images.githubusercontent.com/6522949/236556600-46814f9b-55f3-4f1b-b5c0-b154be3ab08d.png)

**Packages (please complete the following information):**
 - @ng-icons/lucide@25.0.0

**Comment by ashley-hunter** [comment]
Hi, thank you for reporting the issue. An oversight on that package on my part. I have published a fix as part of 25.0.1 which I have just released. That should resolve the issue, if not let me know.
