### ISSUE TITLE
Not working!!

### ISSUE THREAD

**Issue by Mr-Faisal-SGD** [ng-icons/ng-icons#59]
Icons are not working, the only icon that works is the one in example

**Comment by ashley-hunter** [comment]
Hi, would you mind reproducing the issue in StackBlitz to help me understand the issue you are having:

https://stackblitz.com/edit/angular-xok95d?file=src%2Fmain.ts

**Comment by Mr-Faisal-SGD** [comment]
Now you can see that after changing the icon name, it's not working, it was working for only 1st icon

**Comment by ashley-hunter** [comment]
You need to import each icon individually and add them to the provideIcons function before you can use them. If that doesn't help, share a stack blitz showing the issue and I can look into it further.

**Comment by Mr-Faisal-SGD** [comment]
Thanks, sorry, I am new to coding, Thanks alot

**Comment by ashley-hunter** [comment]
No problem, glad that resolved your issue
