### ISSUE TITLE
Icons don't load

### ISSUE THREAD

**Issue by mejobloggs** [ng-icons/ng-icons#65]
Icons are missing on page.

Browser Dev Tools message:
`table-sortable.component.html:13 
No icon named featherEdit was found. You may need to import it using the withIcons function`

The element is present:
`<ng-icon _ngcontent-ng-c1038863478="" name="featherEdit" color="red" _nghost-ng-c2936905789="" ng-reflect-name="featherEdit" ng-reflect-color="red" style="--ng-icon__size: 1em; color: red;"></ng-icon>`

However I think there is supposed to be some SVG script inside the element? There is none

app.module.ts
```import { HttpClientModule } from '@angular/common/http';
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppComponent } from './app.component';
import { TableSortableComponent } from './table-sortable/table-sortable.component';
import { NgIconsModule } from '@ng-icons/core';
import { featherAirplay } from '@ng-icons/feather-icons'

@NgModule({
  declarations: [
    AppComponent,
    TableSortableComponent,
  ],
  imports: [
    BrowserModule, HttpClientModule, NgIconsModule.withIcons({ featherAirplay }),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

```

packages:

{
  "name": "vehicle-app.angular",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --ssl --ssl-cert %APPDATA%\\ASP.NET\\https\\%npm_package_name%.pem --ssl-key %APPDATA%\\ASP.NET\\https\\%npm_package_name%.key --host=127.0.0.1",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "prestart": "node aspnetcore-https"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^16.2.0",
    "@angular/common": "^16.2.0",
    "@angular/compiler": "^16.2.0",
    "@angular/core": "^16.2.0",
    "@angular/forms": "^16.2.0",
    "@angular/platform-browser": "^16.2.0",
    "@angular/platform-browser-dynamic": "^16.2.0",
    "@angular/router": "^16.2.0",
    "@ng-icons/core": "^25.2.0",
    "@ng-icons/feather-icons": "^25.2.0",
    "jest-editor-support": "*",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.2.1",
    "@angular/cli": "~16.2.1",
    "@angular/compiler-cli": "^16.2.0",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.6.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.1.3"
  }
}
```

**Comment by ashley-hunter** [comment]
Hi, thanks for the report, I believe the issue in this case is due to table-sortable being a standalone component. To register an icon in a standalone component, use the provideIcons({}) function rather than NgIconsModule.withIcons({}), you can see an example of this on the getting started page if you choose the Standalone components tab:


![image](https://github.com/ng-icons/ng-icons/assets/20795331/e01cd871-9001-49f7-857b-9d66687985d9)

Hopefully this resolves the issue for you, if not let me know!

**Comment by ashley-hunter** [comment]
Also, I have just noticed, you are trying to use featherEdit, but you've not registered it, you have only registered featherAirplay. You need to register each icon you want to use.
