### ISSUE TITLE
ProvideNgIconLoader doesnt work with ChangeDetection.OnPush

### ISSUE THREAD

**Issue by ct5845** [ng-icons/ng-icons#75]
With the following configuration

```
  changeDetection: ChangeDetectionStrategy.OnPush,
  viewProviders: [
    provideNgIconLoader(name => {
      const http = inject(HttpClient);
      return http.get(`/assets/${name}.svg`, { responseType: 'text' });
    })
  ]
```

The image doesn't get injected into the DOM element, guessing it needs a markForCheck somewhere. Removing the changeDetection (back to default) solves this.

**Comment by ashley-hunter** [comment]
Thank you for the bug report. This has now been resolved:

https://stackblitz.com/edit/stackblitz-starters-vy6bfb?file=src%2Fmain.ts

Check out the 25.6.1 release for the fix.

**Comment by ct5845** [comment]
Great stuff - thanks.
