### ISSUE TITLE
FontAwesome Pack UnAvailable?

### ISSUE THREAD

**Issue by SamurelOrg** [ng-icons/ng-icons#82]
**Describe the bug**
Fontawesome pack missing

**To Reproduce**
For such a popular font pack as fontawesome, I wonder why it's missing in the library. Or there is something I don't know? Thanks.

**Comment by ashley-hunter** [comment]
Thanks for the suggestion. When I looked into it a while back font awesome didn't ship svg files in an npm package to install, they ship their svgs in .js files. While this is not a deal breaker, it made it a bit more effort. Up until now, no one had requested it so I didn't spend the time on it, however, now that it has been requested I will add it this evening. Expect a new release in a few hours with the free font awesome icons.

**Comment by SamurelOrg** [comment]
> This should now be available in the 26.2.0 release.

SOOO great of you, looking forward to that! Thanks Plenty!!!

**Comment by ashley-hunter** [comment]
No problem 😊
