### ISSUE TITLE
Angular17 Component not rendering

### ISSUE THREAD

**Issue by AMM48** [ng-icons/ng-icons#86]
**The bug**
am using Angular17 and when I add the providers line ` viewProviders: [provideIcons({  simpleGithub, simpleLinkedin })]` the component doesn't render.
my project is a standalone project

**Expected behavior**
I expect my component to render and to show the icons

```
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import { simpleGithub, simpleLinkedin } from '@ng-icons/simple-icons';
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, NgIconComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
  viewProviders: [provideIcons({  simpleGithub, simpleLinkedin })]
```

**Browser (please complete the following information):**
 - OS: Windows
 - Browser: Brave (v1.61.104) & Firefox (v119.0)

**Packages**
"@ng-icons/core": "^26.3.0",
"@ng-icons/simple-icons": "^26.3.0",

**Comment by ashley-hunter** [comment]
Hi, thanks for the report. I don't seem to be able to reproduce the issue, it seems to be working as expected for me:

[Stackblitz](https://stackblitz.com/edit/stackblitz-starters-p42w4g?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fmain.ts&title=Angular%20Starter)

Are you able to reproduce the issue in stackblitz so I can investigate further? Or are you getting any build errors or errors in your browser console?

**Comment by AMM48** [comment]
nvm, ng serve was stuck I guess, I just restarted it and it worked. Thanks!

**Comment by ashley-hunter** [comment]
No problem, thanks for letting me know!
