### ISSUE TITLE
add iconsax

### ISSUE THREAD

**Issue by amir141592** [ng-icons/ng-icons#87]
It is a free icon pack that has 6 different variants and over 6,000 icons

**Comment by ashley-hunter** [comment]
Thanks for the suggestion, I have added part of the iconsax library in 26.4.0. Some icon variants did not work well with how our icons are processed and would require quite a bit more work, however you should still have access to 3,000 or so icons from the set and across 3 different variants. If there is a specific variant that you require that is missing let me know and I can look into it further, but hopefully this should suffice for now. Thanks

**Comment by amir141592** [comment]
thank you ashley. i will try them and let you know about it.

**Comment by amir141592** [comment]
i tested it and it works great. these 3 variants is great and enough. thanks

**Comment by ashley-hunter** [comment]
Excellent! No problem! Thank you for letting me know!
