### ISSUE TITLE
Problem with inline styling due to not passing the CSP

### ISSUE THREAD

**Issue by victorgawk** [ng-icons/ng-icons#92]
**Describe the bug**
Since Angular 16, there is an option to build angular and enable CSP (Content-Security-Policy) header without `style-src: unsafe-inline`. 

However, when I try to add the CSP header and display a ng-icon, I am getting this error in the console:
```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-b1b219ce5ba1b187849df1fb4d143f96'". Either the 'unsafe-inline' keyword, a hash ('sha256-qMdGWD0xk5/9kzCYD1p/dkOpR1wkGW9qb9FIubi/EVE='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
```

I found out it was due to the presence of the `style` attribute in the `<svg>` tag.
```html
<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-arrow-repeat" viewBox="0 0 16 16" style="width:var(--ng-icon__size, 1em);height:var(--ng-icon__size, 1em)">
...
</svg>
```

**To Reproduce**
1. Have Angular 16+ with CSP header enabled but without `style-src: unsafe-inline`. Example:
```
Content-Security-Policy: default-src 'self'; style-src 'self' 'nonce-7441868c18e40012f5094f4a1b5a6a02';
```
2. Load ng-icons by registering them in `AppModule.` 

**Expected behavior**
Should have an option to disable the `style` attribute or replace them by a CSS class in order to satisfy the CSP header.

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 121.0.6167.161

**Packages (please complete the following information):**
 - @ng-icons/bootstrap-icons
 - Version 26.5.0

**Comment by ashley-hunter** [comment]
Thank you for the bug report, I have just released v27.0.0 which should resolve you issue. Should it still persist let me know, thank you.

**Comment by ashley-hunter** [comment]
No problem, that would be great, thank you!

**Comment by victorgawk** [comment]
Reproducer: https://stackblitz.com/edit/ng-icons-csp-error-reproducer

The error will be displayed in the browser console:
![image](https://github.com/ng-icons/ng-icons/assets/6736720/aa0ef99c-3158-4b12-85e5-d1c402570e9f)

**Comment by ashley-hunter** [comment]
Thank you for the reproduction environment, very helpful. I have just made a new release with some additional updates. Take a look at this section here on how to configure the library to work with CSP:

https://github.com/ng-icons/ng-icons?tab=readme-ov-file#content-security-policy

Here is your stackblitz updated with the latest version and configuration updates and it appears to be working as expected:

https://stackblitz.com/edit/ng-icons-csp-error-reproducer-mfwddb?file=src%2Fapp%2Fapp.module.ts,src%2Fmain.ts

Any issues let me know, thanks

**Comment by victorgawk** [comment]
Thank you, it worked.
