### ISSUE TITLE
Feature Request: Support throwing error for missing icon

### ISSUE THREAD

**Issue by AbdealiLoKo** [ng-icons/ng-icons#96]
Hi, this is a feature request but a minor one.

We had a bunch of issues in production which were not caught by our tests because we were using ng-icons without adding the icon to `provideIcons`.

I noticed that there is a warning at: https://github.com/ng-icons/ng-icons/blob/b4907295ad5a64fad42a48a165fb5d10bb8f84e5/packages/core/src/lib/components/icon/icon.component.ts#L176

It would be great to see if there is a setting to convert this to an exception that is thrown here or so - so that these can be caught during unit testing

These issues are not caught by the `angular language server` or `tsc` currently :(

**Browser (please complete the following information):**
 - OS: Windows 10 and 11
 - Browser [e.g. chrome, safari]: Chrome Version 122.0.6261.69 (Official Build) (64-bit)

**Packages (please complete the following information):**
 - @ng-icons/bootstrap-icons
 - Version 26.3.0

**Comment by ashley-hunter** [comment]
Thank you for the suggestion! I have added an option where you can configure the logger to throw errors:

https://github.com/ng-icons/ng-icons?tab=readme-ov-file#logging

It is now available in the latest release. Any issues let me know! Thanks
