### ISSUE TITLE
@angular/ssr: NullInjectorError: No provider for InjectionToken Icons Token!

### ISSUE THREAD

**Issue by z3ttee** [ng-icons/ng-icons#98]
Hi all,
I wanted to use this library on a server-rendered app. But I cannot get it to run or even startup.

**Describe the bug**
When using this library on Server-Side-Rendering with `@angular/ssr`, ng-icons causes a NullInjectorError.

**To Reproduce**
A reproduction is provided via this stackblitz:
[https://stackblitz.com/edit/stackblitz-starters-jm48uz?file=src%2Fmain.ts](https://stackblitz.com/edit/stackblitz-starters-jm48uz?file=src%2Fmain.ts)

This app is a simple starter app. What we do is just importing the NgIconsModule in the main component.
Start the app and open the preview. In the browsers console there should be the error.
A screenshot of the error can also be found below.

**Expected behavior**
The module `NgIconsModule` can be imported without errors

**Screenshots**
![image](https://github.com/ng-icons/ng-icons/assets/26038148/623d9035-56a4-4edc-898e-91d2e7a36abb)

**Browser (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 122.0.2365.92

**Packages (please complete the following information):**
 - @ng-icons/core (v27.2.0)
 - @ng-icons/heroicons (v27.2.0)

I hope you can help me find a solution, but for me this looks like a bug that needs to be solved. For any further questions just post an answer here :)

**Comment by ashley-hunter** [comment]
Hi, sure no problem, so that usually means you haven't registered any icons, and from the stackblitz that looks to be the case. See below, you have to register the icons you want to use using provideIcons:

```ts
@Component({
  standalone: true,
  imports: [NgIconsModule],
  providers: [provideIcons({ heroUsers })],
})
export class AppComponent {}
```

Importing NgIconsModule allows you to use the ng-icon component, but doesn't register any icons, that must be done separately.

If you still have the issue after making this change let me know and I will investigate further. Thanks!

**Comment by z3ttee** [comment]
Hi, thanks for the quick response.
I tried importing an icon on the stackblitz, but this didnt work unfortunately:
```javascript
import { NgIconsModule, provideIcons } from '@ng-icons/core';
import { heroUsers } from '@ng-icons/heroicons/outline';

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <h1>Hello!</h1>
    <ng-icon name="heroUsers"></ng-icon>
  `,
  imports: [NgIconsModule],
  providers: [provideIcons({ heroUsers })],
})
export class App {}
```

I think the stackblitz should've been updated also, just if you need repro :)

**Comment by ashley-hunter** [comment]
Great, thank you. So for standalone components use the `NgIcon` as the import instead of `NgIconsModule`, and that should resolve the issue:

https://stackblitz.com/edit/stackblitz-starters-1valpn?file=src%2Fmain.ts

```ts
import { Component } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { heroUsers } from '@ng-icons/heroicons/outline';
import 'zone.js';

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <h1>Hello!</h1>
    <ng-icon name="heroUsers"></ng-icon>
  `,
  imports: [NgIcon],
  providers: [provideIcons({ heroUsers })],
})
export class App {}

bootstrapApplication(App);
```

**Comment by z3ttee** [comment]
Importing just `NgIcon` really fixed the issue in my SSR app. Thanks for your support :), much appreciated
